// A compact but broad emoji set, grouped into categories. Each entry is
// [emoji, keywords] so the picker can search by name/keyword.
export const EMOJI_CATEGORIES = [
  {
    name: 'Smileys', icon: '😀', emojis: [
      ['😀', 'grin happy smile'], ['😃', 'happy smile joy'], ['😄', 'happy laugh smile'], ['😁', 'grin beam'],
      ['😆', 'laugh haha'], ['😅', 'sweat laugh nervous'], ['🤣', 'rofl rolling laugh'], ['😂', 'joy tears laugh'],
      ['🙂', 'slight smile'], ['🙃', 'upside down silly'], ['😉', 'wink'], ['😊', 'blush smile happy'],
      ['😇', 'innocent angel halo'], ['🥰', 'love hearts adore'], ['😍', 'heart eyes love'], ['🤩', 'star struck wow'],
      ['😘', 'kiss blow'], ['😗', 'kiss'], ['😚', 'kiss'], ['😙', 'kiss'], ['🥲', 'happy tear'],
      ['😋', 'yum tasty'], ['😛', 'tongue'], ['😜', 'wink tongue silly'], ['🤪', 'zany crazy'], ['😝', 'tongue squint'],
      ['🤑', 'money mouth rich'], ['🤗', 'hug hands'], ['🤭', 'giggle oops'], ['🤫', 'shh quiet'], ['🤔', 'thinking hmm'],
      ['🤐', 'zipper mouth quiet'], ['🤨', 'raised eyebrow suspicious'], ['😐', 'neutral meh'], ['😑', 'expressionless'],
      ['😶', 'no mouth speechless'], ['😏', 'smirk'], ['😒', 'unamused meh'], ['🙄', 'eye roll'], ['😬', 'grimace'],
      ['🤥', 'lying'], ['😌', 'relieved calm'], ['😔', 'sad pensive'], ['😪', 'sleepy'], ['🤤', 'drool'],
      ['😴', 'sleep zzz'], ['😷', 'mask sick'], ['🤒', 'thermometer sick'], ['🤕', 'bandage hurt'], ['🤢', 'nausea sick'],
      ['🤮', 'vomit sick'], ['🤧', 'sneeze'], ['🥵', 'hot heat'], ['🥶', 'cold freezing'], ['🥴', 'woozy dizzy'],
      ['😵', 'dizzy knocked out'], ['🤯', 'mind blown exploding'], ['🤠', 'cowboy'], ['🥳', 'party celebrate'], ['😎', 'cool sunglasses'],
      ['🤓', 'nerd geek'], ['🧐', 'monocle inspect'], ['😕', 'confused'], ['😟', 'worried'], ['🙁', 'frown'],
      ['☹️', 'frown sad'], ['😮', 'surprise wow'], ['😯', 'hushed'], ['😲', 'astonished shocked'], ['😳', 'flushed embarrassed'],
      ['🥺', 'pleading puppy'], ['😦', 'frown'], ['😧', 'anguished'], ['😨', 'fearful scared'], ['😰', 'anxious sweat'],
      ['😥', 'sad relieved'], ['😢', 'cry tear sad'], ['😭', 'sob cry loud'], ['😱', 'scream fear'], ['😖', 'confounded'],
      ['😣', 'persevere'], ['😞', 'disappointed sad'], ['😓', 'sweat downcast'], ['😩', 'weary tired'], ['😫', 'tired'],
      ['🥱', 'yawn bored'], ['😤', 'triumph steam'], ['😡', 'angry mad rage'], ['😠', 'angry'], ['🤬', 'cursing swearing'],
      ['😈', 'devil smile'], ['👿', 'devil angry'], ['💀', 'skull dead'], ['💩', 'poop'], ['🤡', 'clown'],
      ['👻', 'ghost'], ['👽', 'alien'], ['🤖', 'robot'], ['🎃', 'pumpkin halloween'],
    ],
  },
  {
    name: 'Gestures', icon: '👍', emojis: [
      ['👍', 'thumbs up like yes'], ['👎', 'thumbs down dislike no'], ['👌', 'ok perfect'], ['🤌', 'pinched fingers'],
      ['✌️', 'peace victory'], ['🤞', 'fingers crossed luck'], ['🤟', 'love you'], ['🤘', 'rock horns'], ['🤙', 'call me'],
      ['👈', 'point left'], ['👉', 'point right'], ['👆', 'point up'], ['👇', 'point down'], ['☝️', 'point up index'],
      ['✋', 'raised hand stop'], ['🤚', 'raised back hand'], ['🖐️', 'hand fingers'], ['🖖', 'vulcan spock'], ['👋', 'wave hi bye'],
      ['🤝', 'handshake deal'], ['👏', 'clap applause'], ['🙌', 'raised hands celebrate'], ['👐', 'open hands'], ['🤲', 'palms up'],
      ['🙏', 'pray thanks please'], ['✊', 'fist raised'], ['👊', 'fist bump punch'], ['🤛', 'fist left'], ['🤜', 'fist right'],
      ['💪', 'muscle strong flex'], ['🦾', 'mechanical arm'], ['✍️', 'writing hand'], ['💅', 'nails'], ['🤳', 'selfie'],
      ['👀', 'eyes look'], ['👁️', 'eye'], ['🫶', 'heart hands love'], ['🫡', 'salute'], ['🫰', 'finger heart'],
    ],
  },
  {
    name: 'People', icon: '🧑', emojis: [
      ['👶', 'baby'], ['🧒', 'child'], ['👦', 'boy'], ['👧', 'girl'], ['🧑', 'person'], ['👨', 'man'], ['👩', 'woman'],
      ['🧔', 'beard'], ['👱', 'blond'], ['👴', 'old man'], ['👵', 'old woman'], ['🧓', 'older person'],
      ['👮', 'police officer cop'], ['🕵️', 'detective spy'], ['💂', 'guard'], ['👷', 'construction worker'], ['🤴', 'prince'],
      ['👸', 'princess'], ['👳', 'turban'], ['👲', 'cap'], ['🧕', 'headscarf'], ['🤵', 'tuxedo'], ['👰', 'bride veil'],
      ['🤰', 'pregnant'], ['🎅', 'santa'], ['🤶', 'mrs claus'], ['🦸', 'superhero'], ['🦹', 'supervillain'],
      ['🧙', 'wizard mage'], ['🧚', 'fairy'], ['🧛', 'vampire'], ['🧜', 'merperson'], ['🧝', 'elf'],
      ['🙅', 'no gesture'], ['🙆', 'ok gesture'], ['💁', 'information tipping'], ['🙋', 'raising hand'], ['🙇', 'bow'],
      ['🤦', 'facepalm'], ['🤷', 'shrug'], ['🚶', 'walking'], ['🏃', 'running'], ['💃', 'dancing woman'], ['🕺', 'dancing man'],
    ],
  },
  {
    name: 'Nature', icon: '🐶', emojis: [
      ['🐶', 'dog puppy'], ['🐱', 'cat'], ['🐭', 'mouse'], ['🐹', 'hamster'], ['🐰', 'rabbit bunny'], ['🦊', 'fox'],
      ['🐻', 'bear'], ['🐼', 'panda'], ['🐨', 'koala'], ['🐯', 'tiger'], ['🦁', 'lion'], ['🐮', 'cow'], ['🐷', 'pig'],
      ['🐸', 'frog'], ['🐵', 'monkey'], ['🐔', 'chicken'], ['🐧', 'penguin'], ['🐦', 'bird'], ['🐤', 'chick'],
      ['🦆', 'duck'], ['🦅', 'eagle'], ['🦉', 'owl'], ['🦇', 'bat'], ['🐺', 'wolf'], ['🐗', 'boar'], ['🐴', 'horse'],
      ['🦄', 'unicorn'], ['🐝', 'bee'], ['🐛', 'bug caterpillar'], ['🦋', 'butterfly'], ['🐌', 'snail'], ['🐞', 'ladybug'],
      ['🐜', 'ant'], ['🕷️', 'spider'], ['🦂', 'scorpion'], ['🐢', 'turtle'], ['🐍', 'snake'], ['🦎', 'lizard'],
      ['🐙', 'octopus'], ['🦑', 'squid'], ['🦐', 'shrimp'], ['🦀', 'crab'], ['🐡', 'fish'], ['🐠', 'tropical fish'],
      ['🐟', 'fish'], ['🐬', 'dolphin'], ['🐳', 'whale'], ['🦈', 'shark'], ['🐊', 'crocodile'], ['🐅', 'tiger'],
      ['🐘', 'elephant'], ['🦒', 'giraffe'], ['🐪', 'camel'], ['🐎', 'horse racing'], ['🌵', 'cactus'], ['🌲', 'tree evergreen'],
      ['🌳', 'tree'], ['🌴', 'palm tree'], ['🌱', 'seedling'], ['🌿', 'herb'], ['☘️', 'shamrock'], ['🍀', 'clover luck'],
      ['🍁', 'maple leaf'], ['🍂', 'leaves autumn'], ['🍃', 'leaf wind'], ['🌸', 'blossom'], ['🌷', 'tulip'], ['🌹', 'rose'],
      ['🌺', 'hibiscus'], ['🌻', 'sunflower'], ['🌼', 'flower'], ['💐', 'bouquet'], ['🍄', 'mushroom'],
    ],
  },
  {
    name: 'Food', icon: '🍔', emojis: [
      ['🍎', 'apple'], ['🍏', 'green apple'], ['🍊', 'orange'], ['🍋', 'lemon'], ['🍌', 'banana'], ['🍉', 'watermelon'],
      ['🍇', 'grapes'], ['🍓', 'strawberry'], ['🫐', 'blueberries'], ['🍈', 'melon'], ['🍒', 'cherries'], ['🍑', 'peach'],
      ['🥭', 'mango'], ['🍍', 'pineapple'], ['🥥', 'coconut'], ['🥝', 'kiwi'], ['🍅', 'tomato'], ['🥑', 'avocado'],
      ['🥦', 'broccoli'], ['🥕', 'carrot'], ['🌽', 'corn'], ['🌶️', 'chili pepper spicy'], ['🥔', 'potato'], ['🍠', 'sweet potato'],
      ['🥐', 'croissant'], ['🍞', 'bread'], ['🥖', 'baguette'], ['🧀', 'cheese'], ['🥚', 'egg'], ['🍳', 'fried egg'],
      ['🥞', 'pancakes'], ['🧇', 'waffle'], ['🥓', 'bacon'], ['🍔', 'burger'], ['🍟', 'fries'], ['🍕', 'pizza'],
      ['🌭', 'hot dog'], ['🥪', 'sandwich'], ['🌮', 'taco'], ['🌯', 'burrito'], ['🥗', 'salad'], ['🍝', 'pasta spaghetti'],
      ['🍜', 'ramen noodles'], ['🍲', 'stew'], ['🍛', 'curry'], ['🍣', 'sushi'], ['🍱', 'bento'], ['🍚', 'rice'],
      ['🍙', 'rice ball'], ['🍤', 'shrimp fried'], ['🍦', 'ice cream'], ['🍩', 'donut'], ['🍪', 'cookie'], ['🎂', 'cake birthday'],
      ['🍰', 'cake slice'], ['🧁', 'cupcake'], ['🍫', 'chocolate'], ['🍬', 'candy'], ['🍭', 'lollipop'], ['🍯', 'honey'],
      ['☕', 'coffee tea'], ['🍵', 'tea'], ['🧃', 'juice'], ['🥤', 'soda drink'], ['🍺', 'beer'], ['🍻', 'cheers beers'],
      ['🍷', 'wine'], ['🥂', 'champagne cheers'], ['🍸', 'cocktail'], ['🍹', 'tropical drink'], ['🥃', 'whiskey'], ['🍾', 'champagne bottle'],
    ],
  },
  {
    name: 'Activity', icon: '⚽', emojis: [
      ['⚽', 'soccer football'], ['🏀', 'basketball'], ['🏈', 'american football'], ['⚾', 'baseball'], ['🎾', 'tennis'],
      ['🏐', 'volleyball'], ['🏉', 'rugby'], ['🎱', 'billiards pool'], ['🏓', 'ping pong'], ['🏸', 'badminton'],
      ['🥅', 'goal'], ['🏒', 'hockey'], ['🏑', 'field hockey'], ['🏏', 'cricket'], ['⛳', 'golf'], ['🎯', 'dart bullseye target'],
      ['🎳', 'bowling'], ['🎮', 'game controller'], ['🎲', 'dice'], ['🧩', 'puzzle'], ['♟️', 'chess'], ['🎰', 'slot machine'],
      ['🎨', 'art paint'], ['🎭', 'theater'], ['🎬', 'movie clapper'], ['🎤', 'mic sing'], ['🎧', 'headphones'], ['🎼', 'music'],
      ['🎹', 'piano'], ['🥁', 'drum'], ['🎸', 'guitar'], ['🎺', 'trumpet'], ['🎻', 'violin'], ['🏆', 'trophy win'],
      ['🥇', 'gold medal first'], ['🥈', 'silver medal'], ['🥉', 'bronze medal'], ['🏅', 'medal'], ['🎖️', 'military medal'],
      ['🎗️', 'ribbon'], ['🎫', 'ticket'], ['🎟️', 'tickets'], ['🎪', 'circus'], ['🤹', 'juggling'],
    ],
  },
  {
    name: 'Travel', icon: '✈️', emojis: [
      ['🚗', 'car'], ['🚕', 'taxi'], ['🚙', 'suv'], ['🚌', 'bus'], ['🚎', 'trolley'], ['🏎️', 'race car'], ['🚓', 'police car'],
      ['🚑', 'ambulance'], ['🚒', 'fire truck'], ['🚐', 'van'], ['🚚', 'truck'], ['🚛', 'lorry'], ['🚜', 'tractor'],
      ['🏍️', 'motorcycle'], ['🚲', 'bicycle'], ['🛴', 'scooter'], ['✈️', 'plane flight'], ['🛫', 'takeoff'], ['🛬', 'landing'],
      ['🚀', 'rocket launch'], ['🛸', 'ufo'], ['🚁', 'helicopter'], ['⛵', 'sailboat'], ['🚤', 'speedboat'], ['🛳️', 'ship'],
      ['⚓', 'anchor'], ['🚂', 'train'], ['🚆', 'train'], ['🚇', 'metro subway'], ['🚉', 'station'], ['🚦', 'traffic light'],
      ['🗺️', 'map'], ['🗿', 'moai statue'], ['🗽', 'statue liberty'], ['🗼', 'tower tokyo'], ['🏰', 'castle'], ['🏯', 'japanese castle'],
      ['🏟️', 'stadium'], ['🎡', 'ferris wheel'], ['🎢', 'roller coaster'], ['🎠', 'carousel'], ['⛲', 'fountain'], ['⛱️', 'beach umbrella'],
      ['🏖️', 'beach'], ['🏝️', 'island'], ['🏔️', 'mountain snow'], ['⛰️', 'mountain'], ['🌋', 'volcano'], ['🏕️', 'camping'],
      ['🌅', 'sunrise'], ['🌄', 'sunrise mountains'], ['🌇', 'sunset city'], ['🌆', 'dusk city'], ['🌃', 'night city'], ['🌉', 'bridge night'],
    ],
  },
  {
    name: 'Objects', icon: '💡', emojis: [
      ['⌚', 'watch'], ['📱', 'phone mobile'], ['💻', 'laptop computer'], ['🖥️', 'desktop'], ['🖨️', 'printer'], ['⌨️', 'keyboard'],
      ['🖱️', 'mouse'], ['💽', 'disk'], ['💾', 'floppy save'], ['💿', 'cd'], ['📀', 'dvd'], ['📷', 'camera'], ['📸', 'camera flash'],
      ['📹', 'video camera'], ['🎥', 'movie camera'], ['📞', 'phone call'], ['☎️', 'telephone'], ['📟', 'pager'], ['📠', 'fax'],
      ['📺', 'tv'], ['📻', 'radio'], ['🔋', 'battery'], ['🔌', 'plug power'], ['💡', 'bulb idea light'], ['🔦', 'flashlight'],
      ['🕯️', 'candle'], ['🧯', 'extinguisher'], ['💰', 'money bag'], ['💵', 'dollar cash'], ['💴', 'yen'], ['💶', 'euro'],
      ['💷', 'pound'], ['💳', 'card credit'], ['🧾', 'receipt invoice'], ['💎', 'gem diamond'], ['⚖️', 'scale balance justice'],
      ['🔧', 'wrench tool'], ['🔨', 'hammer'], ['🛠️', 'tools'], ['⚙️', 'gear settings'], ['🔩', 'nut bolt'], ['🧰', 'toolbox'],
      ['🧲', 'magnet'], ['🔗', 'link chain'], ['📎', 'paperclip attach'], ['📌', 'pushpin'], ['📍', 'pin location'], ['✂️', 'scissors cut'],
      ['📏', 'ruler'], ['📐', 'triangle ruler'], ['🖊️', 'pen'], ['🖋️', 'fountain pen'], ['✏️', 'pencil'], ['📝', 'memo note'],
      ['📖', 'book open'], ['📚', 'books'], ['📕', 'book red'], ['📗', 'book green'], ['📘', 'book blue'], ['📙', 'book orange'],
      ['📔', 'notebook'], ['📒', 'ledger'], ['📁', 'folder'], ['📂', 'folder open'], ['🗂️', 'card index'], ['📅', 'calendar date'],
      ['📆', 'calendar'], ['🗓️', 'spiral calendar'], ['📋', 'clipboard'], ['📊', 'bar chart'], ['📈', 'chart up'], ['📉', 'chart down'],
      ['🔍', 'search magnify'], ['🔎', 'search'], ['🔒', 'lock'], ['🔓', 'unlock'], ['🔑', 'key'], ['🗝️', 'old key'],
      ['🔔', 'bell notification'], ['🔕', 'mute bell'], ['📢', 'megaphone announce'], ['📣', 'megaphone'], ['⏰', 'alarm clock'],
      ['⏱️', 'stopwatch'], ['⌛', 'hourglass'], ['⏳', 'hourglass flowing'], ['🧭', 'compass'], ['🌡️', 'thermometer'],
    ],
  },
  {
    name: 'Symbols', icon: '❤️', emojis: [
      ['❤️', 'heart love red'], ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'], ['💙', 'blue heart'],
      ['💜', 'purple heart'], ['🖤', 'black heart'], ['🤍', 'white heart'], ['🤎', 'brown heart'], ['💔', 'broken heart'],
      ['❣️', 'heart exclamation'], ['💕', 'two hearts'], ['💞', 'revolving hearts'], ['💓', 'beating heart'], ['💗', 'growing heart'],
      ['💖', 'sparkling heart'], ['💘', 'heart arrow cupid'], ['💝', 'heart gift'], ['💟', 'heart decoration'], ['❤️‍🔥', 'heart fire'],
      ['💯', '100 hundred perfect'], ['💢', 'anger'], ['💥', 'boom collision'], ['💫', 'dizzy star'], ['💦', 'sweat drops'],
      ['💨', 'dash wind'], ['🕳️', 'hole'], ['💬', 'speech bubble'], ['💭', 'thought bubble'], ['💤', 'zzz sleep'],
      ['✅', 'check mark done yes'], ['✔️', 'check'], ['☑️', 'checkbox'], ['❌', 'cross x no wrong'], ['❎', 'cross mark'],
      ['➕', 'plus add'], ['➖', 'minus'], ['➗', 'divide'], ['✖️', 'multiply'], ['❓', 'question'], ['❗', 'exclamation'],
      ['‼️', 'double exclamation'], ['⁉️', 'interrobang'], ['⚠️', 'warning caution'], ['🚫', 'no forbidden'], ['⛔', 'no entry'],
      ['✨', 'sparkles'], ['⭐', 'star'], ['🌟', 'glowing star'], ['💫', 'dizzy'], ['🔥', 'fire lit hot'], ['🎉', 'party tada celebrate'],
      ['🎊', 'confetti'], ['🎈', 'balloon'], ['🎁', 'gift present'], ['🏁', 'checkered flag finish'], ['🚩', 'flag'],
      ['✳️', 'asterisk'], ['❇️', 'sparkle'], ['♻️', 'recycle'], ['🔰', 'beginner'], ['⚜️', 'fleur de lis'], ['🔱', 'trident'],
      ['🆗', 'ok'], ['🆕', 'new'], ['🆒', 'cool'], ['🆓', 'free'], ['🆙', 'up'], ['🅰️', 'a'], ['🅱️', 'b'],
      ['🔴', 'red circle'], ['🟠', 'orange circle'], ['🟡', 'yellow circle'], ['🟢', 'green circle'], ['🔵', 'blue circle'],
      ['🟣', 'purple circle'], ['⚫', 'black circle'], ['⚪', 'white circle'], ['🟥', 'red square'], ['🟩', 'green square'],
    ],
  },
];

// Flat lookup for quick access to a few defaults.
export const QUICK_REACTIONS = ['👍', '❤️', '😄', '🎉', '✅', '👀', '🙏', '🔥'];
